var drinkRecipes = [
{name:'OLD FASHIONED', image:'Images/drank2.jpg', drinkType: 'whiskey', flavor: 'sour', strength:'xxx', ingredients: ['1 scant teaspoon simple syrup', '2 dashes Angostura Bitters, plus more to taste', '1 medium sized slice orange peel, including pith', '2 ounces good-quality rye or bourbon', '1 maraschino cherry'], recipe: 'In old-fashioned glass, combine simple syrup and bitters. Fill glass halfway with ice, then stir about a dozen times. Add enough ice to fill glass. <br> <br> Squeeze orange peel over glass to extract oils, add peel to glass, and add whiskey. Stir just until drink is cold and alcoholic bite has softened, about a dozen times. Garnish with cherry, swizzle stick, and straw.', music: ''},
{name:'ROSEMARY PEACH MAPLE LEAF COCKTAIL', image:'Images/rosemaryCooler.jpg', drinkType: 'whiskey', flavor: 'fruity', strength:'xxx', ingredients: ['1/4 of a peach, chopped, plus a few slices for garnish', '1 1/2 tablespoons rosemary maple simple syrup (below)', '1 tablespoon strained lemon juice', '1/4 cup rye whiskey (preferably Redemption Rye)', 'Tiny pinch smoked sea salt', 'Ice', 'Rosemary sprig for garnish', 'Sparkling water or club soda, optional'], recipe: 'Muddle together the chopped peach, rosemary maple simple syrup, lemon juice, rye, and salt in a measuring cup or glass. Strain the mixture into a tumbler filled with ice, pressing on the fruit pulp to get out all the good stuff. <br><br> Garnish with the peach slices and rosemary sprig. If you like your drink a little lighter, top it with a splash of sparkling water or club soda.', music: ''},
{name:'BLACKBERRY SMASH', image:'Images/drank2.jpg', drinkType: 'whiskey', flavor: 'botanical', strength:'xxx', ingredients: ['1/2 lemon, sliced', '4 plump fresh blackberries', 'Mint sprig', '2 oz bourbon', '1 oz simple syrup (Mix equal parts water with sugar and heat only until sugar dissolves. Cool before using)'], recipe: 'Muddle lemon slices, blackberries and mint in a cocktail shaker. Add bourbon and simple syrup and fill shaker with ice. Shake at least 10 times and strain into a short glass filled with ice.Garnish with mint.', music: ''},
{name:'SMOKEY WHISKEY SOUR', image:'Images/drank2.jpg', drinkType: 'whiskey', flavor: 'smoky', strength:'xxx', ingredients: ['3 ounces bourbon/whisky of your choice', '2 ounces of Smoky Honey Simple Syrup', '1 1/2 ounces of lemon juice', 'Smoky Honey Simple Syrup', '1/4 cup water', '1 cup Billy Bee Honey', '1 tea bag of Lapsang Souchong Tea'], recipe: 'Fill a large cocktail shaker full of ice, then add in all of the ingredients. Shake until the outside of the shaker is completely chilled (and thus so is the cocktail inside) then strain into two glasses.To make the simply syrup, Combine the honey and water in a medium sized saucepan. Place the tea bag into the mixture (I remove the tag and just let it float). Bring to a simmer; continue to simmer for 5 minutes, stirring gently once in a while. Remove from the heat. Remove the tea bag then refrigerate until using.', music: ''},
{name:'SPICY GINGER HOT TODDY', image:'Images/drank2.jpg', drinkType: 'whiskey', flavor: 'spicy', strength:'xxx', ingredients: ['2 cups water', '1 1/2-inch ginger root, thinly sliced', '4 to 6 cloves', '1 lemon, halved', 'Honey, as needed', 'Rum or bourbon, as needed', 'Lemon slices, as garnish'], recipe: 'In a medium saucepan, add water, gingerroot slices and cloves. Squeeze lemon juice into the saucepan, adding lemon halves into the liquid. Bring to a boil over high heat, and then reduce to medium heat, so the liquid is bubbling. <br><br>Cook for 10 to 20 minutes, until the mixture has reduced and has enough of a gingery taste to your liking. Strain, removing cloves, lemon halves and ginger from the liquid. Pour into two mugs. Add enough honey and rum or bourbon to your tastes. Garnish with lemon slices, and serve.', music: ''},
{name:'BOURBON SLUSH PUNCH', image:'Images/bourbonPunch.jpg', drinkType: 'whiskey', flavor: 'frosty', strength:'xxx', ingredients: ['1 cup water', '2 tea bags (whatever you like for iced tea)', '1 cup bourbon', '1/4 cup granulated sugar', '1 1/2 cups orange juice (about 3 well-squeezed oranges)', '6 tablespoons lemon juice (about 2 lemons)', '16 to 17 ounces (about 5 cups of small pieces of ice) ice cubes', 'Mint sprigs or lemon slices, for garnish'], recipe: 'Boil 1 cup water for tea. Add the tea bags and let steep until cool. Discard the tea bags and set aside. Pour tea into a pitcher. Add bourbon, sugar, orange juice and lemon juice and refrigerate until needed. Don’t worry about stirring the sugar so that it dissolves; after 30 minutes in the fridge, it will have.<br><br> To serve: Shake or stir punch base to ensure ingredients are evenly distributed. To make two liters of punch, add base and full amount of ice cubes to your blender, blending until the ice is crushed and slushy. For each individual glass of punch, place 1/2 cup punch base and slightly heaped 1/2 cup small pieces of ice (mine were chipped off an ice block; don’t ask) and blend until slushy. Add an extra whole ice cube or two to glasses if desired. Garnish glass with a sprig of mint or slice of lemon.', music: ''},

{name:'LEMON DROP', image:'Images/lemonDrop.jpg', drinkType: 'vodka', flavor: 'sour', strength:'xxx', ingredients: ['1 Part Absolut Vodka', '2/3 Part Lemon Juice', '1/3 Part Triple Sec'], recipe: 'Fill a shaker with ice cubes. Add all ingredients. Shake and strain into a chilled shot glass.', music: ''},
{name:'PEAR MARTINI', image:'Images/pearMartini.jpg', drinkType: 'vodka', flavor: 'fruity', strength:'xxx', ingredients: ['1 1/2 Parts Absolut Pears', '1/2 Part Lemon Juice', '3/4 Part Simple Syrup', '1/2 Part Pear Puree', '1 Slice Pear'], recipe: 'Fill a shaker with ice cubes. Add all ingredients. Shake and strain into a chilled cocktail glass. Garnish with pear.', music: ''},
{name:'EARL GREY MARTINI', image:'Images/earlGrey.jpg', drinkType: 'vodka', flavor: 'botanical', strength:'xxx', ingredients: ['1 1/2 fl ounce strong earl grey tea, chilled', '3/4 fl ounce freshly squeezed lemon juice', '1/2 fl ounce simple syrup', '1 1/2 fl ounces gin', '1 egg white', 'Ice', 'Lemon wedge or twist, to garnish', 'Sugar to rim the martini glass', 'Strong earl grey tea'], recipe: 'Fill a shaker with ice cubes. Add all ingredients. Shake and strain into a chilled cocktail glass. Garnish with pear.', music: ''},
{name:'SMOKEHOUSE MARTINI', image:'Images/smokehouse.jpg', drinkType: 'vodka', flavor: 'smoky', strength:'xxx', ingredients: ['2.5 oz Vodka', '.25 oz Blended Scotch whisky', 'Lemon twist'], recipe: 'Add both ingredients to a mixing glass and fill with ice. Stir, and strain into a Martini glass. Garnish with a lemon twist.', music: ''},
{name:'SPICY WHITE RUSSIAN', image:'Images/whiteRussian.jpg', drinkType: 'vodka', flavor: 'spicy', strength:'xxx', ingredients: ['1 OZ. Cinnamon vodka', '.5 OZ. Kahlua', '.5 OZ Half and Half', 'Cinammon Sticks', 'Cayenne Pepper'], recipe: 'Add vodka, kahlua, and half and half in ice filled shakeer. Shake, shake, shake, shake. Pour over ice. Garnic with cinnamon spice and cayenne pepper and enjoy!', music: ''},
{name:'VODKA LEMONADE SMASH', image:'Images/lemonadeSlush.jpg', drinkType: 'vodka', flavor: 'frosty', strength:'xxx', ingredients: ['12 oz frozen lemonade concentrate', '12 oz vodka', '24 oz cold water', 'zest from 1 lemon', 'Lemon slices to garnish, if desired'], recipe: 'In a large bowl combine lemonade concentrate, vodka, water and lemon zest. Stir together until well combined. Pour lemonade mixture into a shallow freezer-safe pan. Freeze mixture for at least 8 hours or overnight, stirring once halfway through freezing. To serve, fluff ice crystals with a fork and spoon into glasses for serving. Garnish with lemon slices, if desired.', music: ''},

{name:'GRAPEFRUIT MOJITOS', image:'Images/grapefruitMojito.jpg', drinkType: 'rum', flavor: 'sour', strength:'xxx', ingredients: ['2 large pink grapefruits', '2-3 limes', '2 tablespoons honey', '3-4 ounces white rum', 'a handful of mint leave', 'sparking water'], recipe: 'Squeeze the juice out of the grapefruits and limes. Filter through a fine mesh strainer to remove seeds and pulp. Stir the honey in with the juices until dissolved (sometimes I give the mixture a few seconds in the microwave to get the honey really incorporated, otherwise it clumps together when you add the ice). <br><br>For one drink, vigorously shake the following in a cocktail. Pour the drink into the glass with or without the ice (your call! we leave the ice in). Give it all a good stir to get the mint leaves going and top it off with sparking water.', music: ''},
{name:'BLUEBERRY MOJITOS', image:'Images/mojito.jpg', drinkType: 'rum', flavor: 'fruity', strength:'xxx', ingredients: ['8 blueberries (fresh or frozen and thawed), plus more for serving', '2 tablespoons (1 ounce) fresh squeezed lime juice', '2 teaspoons sugar', '8 fresh mint leaves, plus more for serving', '1/4 cup (2 ounces) white rum', 'Ice', '2 tablespoons (1 ounce) club soda', 'Lime slice for serving'], recipe: 'Add blueberries, lime juice, sugar and eight mint leaves to a cocktail shaker. Use the end of a wooden spoon or cocktail muddler to bash (or muddle) the mint into the lime juice and sugar. This releases oils from the mint, breaks up the blueberries and helps the sugar dissolve into the lime juice.<br><br>Add rum, stir well then pour into a glass filled with ice, leaving about an inch of room then top with club soda. Garnish with extra blueberries, mint leaves and a lime slice.', music: ''},
{name:'ROSEMARY TANGERINE COOLER', image:'Images/rosemaryCooler.jpg', drinkType: 'rum', flavor: 'botanical', strength:'xxx', ingredients: ['2 tablespoons raw sugar plus more', '4 tangerines, halved crosswise', '16 rosemary sprigs, divided', '2 cups white rum'], recipe: 'Heat a cast-iron skillet or griddle over high heat, or on a grill grate. Pour some raw sugar into a small plate. Dip cut sides of tangerines into sugar. Scatter 8 rosemary sprigs in skillet; add tangerines, cut side down. Cook until sugar caramelizes, about 2 minutes. <br><br>Let cool. Quarter tangerines; discard rosemary. Place tangerines in a pitcher, add 2 Tbsp. raw sugar, and muddle to release juices. Add rum and 6 cups ice; stir until pitcher is frosty. Divide among glasses; garnish with remaining 8 rosemary sprigs.', music: ''},
{name:'SMOKEY APPLE MOUNTAIN', image:'Images/applePie.jpg', drinkType: 'rum', flavor: 'smoky', strength:'xxx', ingredients: ['1 oz. Ole Smoky Original Moonshine', '3 oz. Ole Smoky Apple Pie Moonshine', '1 oz. Cranberry Juice'], recipe: 'Mix well in a glass over ice. Garnish with an apple slice', music: ''},
{name:'SPICED GINGER GRAPEFRUIT RUM PUNCH', image:'Images/grapefruitPunch.jpg', drinkType: 'rum', flavor: 'spicy', strength:'xxx', ingredients: ['1 1/2 cups Malahat Spiced Rum', '2 bottles (12 oz) ginger beer', '2 cups fresh squeezed grapefruit juice', '1 bottle champagne or sparkling wine', '2 tbsp fresh mint leaves', '1 grapefruit (thinly sliced)'], recipe: 'Add the rum, ginger beer, grapefruit juice and champagne to a large punch bowl. Add ice to the bowl. Mix in the mint leaves and sliced grapefruit.', music: ''},
{name:'PINA COLADA', image:'Images/pinaColada.jpg', drinkType: 'rum', flavor: 'frosty', strength:'xxx', ingredients: ['1/2 fresh pineapple, peeled, cut into 1 1/2-inch pieces', '6 ounces sweetened cream of coconut (preferably Coco López)', '2 ounces unsweetened coconut milk', '8 ounces white rum', '2 tablespoons fresh lime juice', '2 ounces dark rum (optional)', 'Maraschino cherries and lime wedges (for serving)'], recipe: 'Place pineapple pieces in a resealable plastic bag, laying them flat. Freeze until solid, at least 3 hours. Shake cream of coconut and coconut milk in their cans before measuring. <br><br>Puree pineapple, cream of coconut, coconut milk, white rum, lime juice, and 3 cups ice (about 15 oz.) in a blender until smooth. Transfer blender cup to freezer and freeze until mixture is thickened (it should be the consistency of a milkshake), 25–35 minutes. Blend again until mixture is the perfect slushy frozen drink consistency. Divide among glasses. Top off each with 1/2 oz. dark rum, if using, and garnish each with a cherry and lime wedge.', music: ''},

{name:'TEQUILA SPRITZER', image:'Images/tequilaSpritzer.jpg', drinkType: 'tequila', flavor: 'sour', strength:'xxx', ingredients: ['2 cups tequila blanco', '1/2 cup Aperol',  '1/2 cup sweet vermouth', '8 dashes orange bitters', '2 large grapefruits, each cut into 8 wedges', '1 1-liter bottle chilled club soda'], recipe: 'Combine tequila, Aperol, vermouth, and bitters in a leakproof airtight container, do this ahead it will be your base. For each cocktail, pour ⅓ cup base into an ice-filled glass. Squeeze juice from 1 grapefruit wedge into glass; discard wedge. Top off with 4 oz. club soda and garnish with a fresh grapefruit wedge.', music: ''},
{name:'PALOMA', image:'Images/paloma.jpg', drinkType: 'tequila', flavor: 'fruity', strength:'xxx', ingredients: ['Kosher salt', '1 grapefruit wedge', '1/4 cup fresh grapefruit juice', '1 tablespoon fresh lime juice', '1 teaspoon sugar', '1/4 cup mezcal or tequila', '1/4 cup club soda'], recipe: 'Pour some kosher salt on a plate. Rub half of rim of a highball glass with grapefruit wedge; dip rim of glass in salt. Combine grapefruit juice, lime juice, and sugar in glass; stir until sugar is dissolved. Stir in mescal, add ice, and top off with club soda. Garnish with grapefruit wedge.', music: ''},
{name:'BLACKBERRY SAGE SMASH', image:'Images/sageSmash.jpg', drinkType: 'tequila', flavor: 'botanical', strength:'xxx', ingredients: ['8 plump blackberries, the bigger the better', '1 ounce sage simple syrup (1/2 cup unrefined sugar and 1/2 cup water, 5 sage leaves)', '2 ounces Tequila', 'crushed ice', 'tonic water', 'blackberry, as garnish', 'sage leave, as garnish'], recipe: "Let's make the simple syrup first, place all the ingredients for the simple syrup into a sauce pan, bring to a boil, then turn off the heat and let sit until cooled. Strain into a glass bottle and use for fall cocktails. Cocktail Time: Place 8 blackberries and 1 ounce of the simple syrup into a large glass and muddle.  Add the bourbon and give a quick muddle. Fill a cocktail glass with crushed ice and pour in the blackberry bourbon mixture. Stir. Top with some tonic water. Garnish.", music: ''},
{name:'MEZCAL MARGERITA', image:'Images/mezcal.jpg', drinkType: 'tequila', flavor: 'smoky', strength:'xxx', ingredients: ['2 ounces of mezcal', '1 ounce of fresh lime juice', '1/2 ounce of agave syrup (light agave dissolved in an equal amount of hot water)'], recipe: 'Shake that all up, strain it into a cocktail glass and garnish with a lime wheel.', music: ''},
{name:'HABENERO TEQUILA FIZZ', image:'Images/tequilaFizz.jpg', drinkType: 'tequila', flavor: 'spicy', strength:'xxx', ingredients: ['1 egg white', '1/2-ounce lemon juice', '1/2-ounce simple syrup', '2 ounces tequila', 'Club soda'], recipe: 'Combine all the ingredients, except the club soda, in a mixing glass or shaker and shake well. Pour into a Collins glass filled with ice and top with club soda.', music: ''},
{name:'SLUSHY TEQUILA SUNRISE', image:'Images/sunrise.jpg', drinkType: 'tequila', flavor: 'frosty', strength:'xxx', ingredients: ['Margarita or coarse sea salt, for rimming glass', '1 lime wedge, for rimming glass', '1/2 cup frozen orange juice concentrate', '1 1/2 cups orange juice', '3/4 cup (6 ounces) tequila', '2 tablespoons (1 ounce) Cointreau or triple sec', '2 tablespoons lime juice', '3 cups crushed ice', '1/4 cup grenadine', 'For Garnish: 4 orange slices and 4 maraschino cherries'], recipe: 'Spread a layer of salt in a shallow dish. Run lime wedge around the rims of 4 highball glasses to moisten; dip rims in salt. <br><br>Place orange juice concentrate, orange juice, tequila, Cointreau, and lime juice in a blender. Add ice and pulse until smooth. Divide margarita evenly among glasses. <br><br>Tilt glasses and pour 1 tablespoon grenadine down the side of each drink; grenadine will sink to the bottom and create a sunset effect. Garnish with orange slices and maraschino cherries and serve.', music: ''},

{name:'POMEGRANATE CHAMPAGNE COCKTAIL', image:'Images/pomegranate.jpg', drinkType: 'champagne', flavor: 'sour', strength:'xxx', ingredients: ['1 tablespoon pomegranate simple syrup', 'lime juice', 'pomegranate seeds', '1 glass of champagne', '1/2 teaspoon szechuan button petals'], recipe: 'Pour the simple syrup into a champagne glass.  Lightly drizzle the champagne into the glass, do not disturb the simple syrup and do not stir. Top with lime juice and seeds. Sprinkle the petals over the top.  Serve.  Drink.' , music: ''},
{name:'PEACH BELLINI', image:'Images/mimosa.jpg', drinkType: 'champagne', flavor: 'fruity', strength:'xxx', ingredients: ['2 ripe peaches, seeded and diced', '1 tablespoon freshly squeezed lemon juice', '1 teaspoon sugar', '1 bottle chilled prosecco sparkling wine'], recipe: 'Place the peaches, lemon juice, and sugar in the bowl of a food processor fitted with a steel blade and process until smooth. Press the mixture through a sieve and discard the peach solids in the sieve. Place 2 tablespoons of the peach puree into each Champagne glass and fill with cold prosecco. Serve immediately.' , music: ''},
{name:'THYME GRAPEFRUIT CHAMPAGNE PUNCH', image:'Images/thyme.jpg', drinkType: 'champagne', flavor: 'botanical', strength:'xxx', ingredients: ['2 cups grapefruit juice', '2 cups orange juice', '1/2 cup fresh-squeezed lemon juice', '1/2cup fresh-squeezed lime juice', 'pinch of kosher salt', '1/2 cup thyme simple syrup', '1 bottle champagne'], recipe: 'Place sugar and pinch of salt in bottom of pitcher. Add grapefruit, orange, lemon and lime juice. Stir in simple syrup. Refrigerate until mixture is well chilled. Add champage and stir. Pour punch into stemware. Add a sprig of thyme and serve.' , music: ''},
{name:'SMOKEY CANTALOUPE FIZZ', image:'Images/cantaloupe.jpg', drinkType: 'champagne', flavor: 'smoky', strength:'xxx', ingredients: ['1 1/2 ounces of Mezcal', 'Cantaloupe lime agua fresca', 'Ice', 'Champagne','Lime slice, garnish'], recipe: 'Put some ice into a cocktail glass. Add the fresca and Mezcal. Stir. Top off with champagne. Garnish with lime slice. Serve. Sip.' , music: ''},
{name:'PINK PEPPERCORN CHAMPAGNE PUNCH', image:'Images/peppercorn.jpg', drinkType: 'champagne', flavor: 'spicy', strength:'xxx', ingredients: ['For the Simple Syrup:', '1/2 cup cane sugar', '1/2 cup water', '2 tablespoons pink peppercorns', 'For the cocktail:', '24 ounces rosé wine (I used Bridge Lane)', '12 ounces gin (I used the Botanist)', '24 ounces white grape juice', '3 ounces cranberry liqueur (I used Leopold Bros.)', '3 ounces pink peppercorn syrup', '12 ounces chilled champage', 'Ice', 'Cranberries, for garnish (sugar them, if you have the time)', 'Cranberry and rosemary ice cubes, for garnish'], recipe: 'For the pink peppercorn syrup: In a small saucepan, combine the cane sugar, water, and pink peppercorns. Bring to a slow boil over medium-high heat and then lower the heat to a slow simmer, until sugar is dissolved. Remove from heat, steep for 20 minutes, discard solids, and let cool completely. <br><br>In a large pitcher or punch bowl, combine the rosé, gin, white grape juice, cranberry liqueur, and pink peppercorn syrup. Stir until incorporated and chill in the refrigerator until you are ready to enjoy.You can make this portion of the cocktail a day ahead and store it in the refrigerator; just give the mixture a good stir before serving. <br><br>For the cocktail: When you are ready to serve the cocktail, fill your pitcher or punch bowl with ice, and add the chilled cocktail mixture. Quickly top with the champagne, taste for balance, and give the mixture a gentle stir. Prep individual cocktail glasses with cranberry and rosemary ice cubes; add the finished rosé, gin, and pink peppercorn cocktail; and garnish with cranberry skewers.' , music: ''},
{name:'FRENCH 75 POPSICLES', image:'Images/popsicles.jpg', drinkType: 'champagne', flavor: 'frosty', strength:'xxx', ingredients: ['12 oz. of champagne', '4 oz. of cognac or gin', '4 oz. of simple syrup', '3 oz. of fresh lemon juice'], recipe: 'Combine all ingredients together into a large measuring cup, then evenly distribute in your popsicle molds, leaving about 1/4 inch of room at the top. (You’ll have around 3 oz. left over after filling the molds.)' , music: ''},

{name:'RHUBARB GIN SOUR', image:'Images/rhubarb.jpg', drinkType: 'gin', flavor: 'sour', strength:'xxx', ingredients: ['1 oz London Dry Gin', '4 oz Rhubarb simple syrup (recipe below)', '1 oz lemon juice', '1 egg white', 'Rhubarb Simple Syrup:', '1 cup chopped rhubarb', '2 cups water', '2 cups sugar'], recipe: 'Pour all ingredients into a cocktail shaker. Add plenty of ice and shake for 30 seconds. Strain into a rocks glass filled with crushed ice. Cheers! <br><br>For Rhubarb Simple Syrup: Combine all in a saucepan. Heat over medium heat until mixture boils. Stir, and let simmer on low for 15 minutes. Strain out rhubarb, discard rhubarb pieces. Let syrup cool.', music: ''},
{name:'SLOE GIN SPRITZ', image:'Images/sloegin.jpg', drinkType: 'gin', flavor: 'fruity', strength:'xxx', ingredients: ['4 ounces dry Prosecco or other sparkling white wine', '1 ounce sloe gin', 'Club soda', 'Blueberries, mint sprig (for serving)'], recipe: 'Add the club soda to a Fizz or Collins glass and set aside. Add the remaining ingredients to a shaker and shake without ice for about 10 seconds. Add 3 or 4 ice cubes and shake very well. Double-strain into the prepared glass.', music: ''},
{name:'SAGE HONEY GIN FIZZ', image:'Images/sage.jpg', drinkType: 'gin', flavor: 'botanical', strength:'xxx', ingredients: ['- 3 ounces gin', '1/2 – 1 ounce honey sage syrup, depending on your desired level of sweetness (recipe below)', '1/2 ounce fresh lime juice', '5 ounces club soda', 'fresh sage leaves for garnish', 'Honey sage syrup:', '1/2 cup honey', '1/2 cup water', '5-6 fresh sage leaves'], recipe: 'Combine all ingredients in a saucepan and bring to a boil, stirring constantly. Reduce heat to low and stir until it appears that all of the honey has dissolved. Remove from heat and let sit until completely cooled to room temperature. Remove sage leaves before using. This can be made well ahead of time and store in a jar in the fridge. <br><br>For the smoked honey rim: Honey, fine smoked sea salt, finely crumbled bacon (Note: one slice of bacon will garnish about 4-6 glasses if you only coat 1/4 of the rim.) <br><br>On a plate, combine bacon and salt, mixing well to combine. Take your glass and rub a drop of honey on 1/4 of the rim, then dip, twist and turn it around in the bacon salt, coating it. I don’t recommend coating more than 1/4 of 1/3 of the rim because it will overpower the honey sage. If you cannot find smoked sea salt, regular can be used in place of it. If you are vegetarian or prefer not to use bacon, the salt is just fine too.<br><br>Fill the glass with a few sage leaves and ice cubes, then add gin, 1/2 ounce of syrup and lime juice, stirring well. Pour in club soda, stirring a bit more, then taste and determine if the drink has enough sweetness. If not, add a bit more. Garnish with an extra sage leaf and serve. Enjoy!', music: ''},
{name:'SMOKEY GRAPEFRUIT GIN AND TONIC', image:'Images/smokygfruit.jpg', drinkType: 'gin', flavor: 'smoky', strength:'xxx', ingredients: ['1 half-wheel slice of pink grapefruit', '2 oz. gin', '1⁄2 oz. grapefruit juice', '2 oz. tonic', '2 oz. soda', 'Sea salt'], recipe: 'Build a medium-heat fire in a charcoal grill, or heat a gas grill to medium. (Alternatively, heat a cast-iron grill pan over medium-high.) Place grapefruit on grill and cook, turning once, until lightly charred, about 1 minute. Remove from heat and set aside. <br><br>To an ice-filled rocks glass, add gin and grapefruit juice. Top with tonic and soda, and garnish with grilled grapefruit slice sprinkled with sea salt.', music: ''},
{name:'PINEAPPLE JALAPENO GIN SHRUB', image:'Images/pineapple.jpg', drinkType: 'gin', flavor: 'spicy', strength:'xxx', ingredients: ['1 small pineapple, peeled, cored and cut into slices', '16 ounces organic apple cider vinegar', 'gin', '1 1/4 cup unrefined sugar', '2 teaspoons Tabasco Green Jalapeño Sauce'], recipe: 'Place the pineapple slices into a large glass jar add the vinegar. Seal with a lid. Turn the jar over once, then place on the counter. Let infuse for 4 – 6 days, shaking once a day.  I infused for 6 days as I wanted a more intense pineapple taste. Filter through cheesecloth. Place the pineapple vinegar into a medium saucepan, add the sugar and bring to a boil. When the sugar dissolves, skim off the top layer, remove from the heat and set aside to cool. Filter through clean cheesecloth. Stir in the gin and Tabsco. Bottle. Keep in the refrigerator until ready to use.', music: ''},
{name:'RASPBERRY LIME GIN RICKY SLUSH', image:'Images/ginslush.jpg', drinkType: 'gin', flavor: 'frosty', strength:'xxx', ingredients: ['2 1/2 cups ice cubes', '1 1/2 cups sparkling water', '1/2 cup gin (such as Bluecoat American Dry Gin)', '6 tablespoons sugar', '1/4 cup fresh lime juice', '8 ounces fresh raspberries, frozen', 'Lime wedges (optional)'], recipe: 'Combine ingredients in a blender. Blend until smooth. Serve slushies with lime wedges, if desired.', music: ''},
]


$(document).ready(function() {
  var drinkType = localStorage.getItem('drinkType');
  var flavor = localStorage.getItem('flavorType');

  for(var i = 0; i < drinkRecipes.length; i++) {
    var drinkObj = drinkRecipes[i];
      if(drinkObj.drinkType === drinkType && drinkObj.flavor === flavor) {
    renderRecipe(drinkObj);
    break;
    }
  }
});

var renderRecipe = function(recipeObj) {
  $('.drinkTitle').html(recipeObj.name);
  $('.spiritsList').html(recipeObj.drinkType);
  $('.flavorList').html(recipeObj.flavor);
  $('.recipeText').html(recipeObj.recipe);
  $('#drinkImage').attr('src', recipeObj.image);
  // $('#muzak').attr('href', recipeObj.music);

  for(var i = 0; i < recipeObj.ingredients.length; i++) {
    var ingredient = recipeObj.ingredients[i];
    $('.ingredientList').append('<li class="ingredients" src=ingredient>' + ingredient + '</li>');
  }
}

$( '.surprise' ).click(function(event) {
  var number = Math.floor (Math.random() * (drinkRecipes.length));
  
  var recipeToRender = drinkRecipes[number];
  renderRecipe(recipeToRender);

  localStorage.setItem('drinkType', recipeToRender.drinkType);
  localStorage.setItem('flavorType', recipeToRender.flavor);

  window.location = 'loader.html';
});

$(".alc").click(function(event) {
  var elem = $(this);
  var drinkType = elem.attr('drink');
  
  localStorage.setItem('drinkType', drinkType);
  window.location = 'flavor.html'
});

$(".taste").click(function(event) {
  var elem = $(this);
  var flavorType = elem.attr('flavor');

  localStorage.setItem('flavorType', flavorType);
  window.location = 'loader.html';

});